name: Lint and Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt

      - name: Black
        uses: microsoft/action-python@0.7.0
        with:
          python_version: '3.12'
          black: true
          workdir: "."

      - name: Bandit
        uses: microsoft/action-python@0.7.0
        with:
          python_version: '3.12'
          bandit: true
          workdir: "."

      - name: Pylint
        uses: microsoft/action-python@0.7.0
        with:
          python_version: '3.12'
          pylint: true
          workdir: "."
          
      - name: Pyright
        uses: microsoft/action-python@0.7.0
        with:
          python_version: '3.12'
          pyright: true
          workdir: "."
          
      - name: Flake8
        uses: microsoft/action-python@0.7.0
        with:
          python_version: '3.12'
          flake8: true
          workdir: "."

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:
          python_version: '3.12'
          pytest: false
          testdir: "tests/"
          workdir: "."